const MINUTES_IN_HOUR = 60;
const MILLISECONDS_IN_SECOND = 1000;

const UPDATE_CHECK_INTERVAL_MINUTES = 5;
const INITIAL_UPDATE_DELAY_SECONDS = 1;

export const UPDATE_CHECK_INTERVAL =
  UPDATE_CHECK_INTERVAL_MINUTES * MINUTES_IN_HOUR * MILLISECONDS_IN_SECOND;

export const INITIAL_UPDATE_DELAY =
  INITIAL_UPDATE_DELAY_SECONDS * MILLISECONDS_IN_SECOND;
